Changes from shellcheck

diff --git a/src/piphoto-sync b/src/piphoto-sync
--- a/src/piphoto-sync
+++ b/src/piphoto-sync
@@ -24,51 +24,53 @@ if [ -z "${mount_point:-}" ]; then
     exit 1
 fi
 
+if [ -z "${remove_after_sync:-}" ]; then
+    echo "remove_after_sync is not set, defaulting to 0."
+    remove_after_sync=0
+fi
+
 # Ssh into the remote host in master mode
-ssh -nNfM $dest_host
+ssh -nNfM "$dest_host"
 
 # Iterate over the the images in the directory
 LAST_CREATED=""
-for file in $(find $mount_point)
-do
+while IFS= read -r -d '' file; do
     echo "Processing $file"
 
-    if [ ! -d "$file" ] ; then
+    # Extract the date it was taken
+    date=$(exiftool -T -createdate -d  "%Y-%m-%d" "$file" || true)
+    year=$(date --date="$date" "+%Y" || true)
+    remote_path="$dest_path/$year/$date/"
 
-        # Extract the date it was taken
-        date=$(exiftool -T -createdate -d  "%Y-%m-%d" $file || true)
-        year=$(date --date="$date" "+%Y" || true)
-        remote_path="$dest_path/$year/$date/"
-
-        if [ -z "$date" ] || [ -z "$year" ] || [ "$date" == "-" ] ; then
-            >&2 echo "Could not infer date from file \"$file\""
-        else
-            # Create a remote directory if we think we need to
-            if [ "$LAST_CREATED" != "$remote_path" ]; then
-                echo "Creating remote path $remote_path"
-                ssh $dest_host "mkdir -p $remote_path"
-                LAST_CREATED="$remote_path"
-            fi
-
-            # Copy the file to the remote directory
-            copied=0
-            rsync -a -e ssh $file $dest_host:"$remote_path" || copied=$?
-            if [ $copied -ne 0 ] ; then
-                >&2 echo "Could not copy $file to $dest_host:$remote_path"
-            else
-                echo "Copied $file to $dest_host:$remote_path"
-                # remove the source file if asked.
-                if [ $remove_after_sync -eq 1 ] ; then rm -f "$file" ; fi
-            fi
-        
+    if [ -z "$date" ] || [ -z "$year" ] || [ "$date" == "-" ] ; then
+        >&2 echo "Could not infer date from file \"$file\""
+    else
+        # Create a remote directory if we think we need to
+        if [ "$LAST_CREATED" != "$remote_path" ]; then
+            echo "Creating remote path $remote_path"
+            ssh "$dest_host" "mkdir -p $remote_path" < /dev/null
+            LAST_CREATED="$remote_path"
         fi
-    fi
-done
 
-if [ $remove_after_sync -eq 1 ] ; then
+        # Copy the file to the remote directory
+        copied=0 
+        rsync -a -e ssh "$file" "$dest_host":"$remote_path" || copied=$?
+        if [ "$copied" -ne 0 ] ; then
+            >&2 echo "Could not copy $file to $dest_host:$remote_path"
+        else
+            echo "Copied $file to $dest_host:$remote_path"
+            # remove the source file if asked.
+            if [ "$remove_after_sync" -eq 1 ] ; then rm -f "$file" ; fi
+        fi
+    
+    fi
+
+done< <(find "$mount_point" -type f -print0)
+
+if [ "$remove_after_sync" -eq 1 ] ; then
     sync
 fi
 
 # Terminate the ssh connection
 
-ssh -O exit $dest_host
+ssh -O exit "$dest_host"
